"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var service_decorator_1 = require("./service.decorator");
exports.Service = service_decorator_1.Service;
var method_decorator_1 = require("./method.decorator");
exports.Method = method_decorator_1.Method;
var method_hook_decorator_1 = require("./method.hook.decorator");
exports.HookMethod = method_hook_decorator_1.HookMethod;
var service_hook_decorator_1 = require("./service.hook.decorator");
exports.HookService = service_hook_decorator_1.HookService;
